-- ============================================================================
-- NIET MEER NODIG — bewaard voor referentie
-- ============================================================================
-- De cron-jobs zijn op 2026-06-11 herschreven (migratie crons_via_anon_jwt) en
-- gebruiken de anon key (publiek by design) als Bearer voor de verify_jwt-gate
-- van de edge functions. De functions gebruiken intern hun eigen
-- service-role-omgeving; er hoeft dus géén service-key in de vault.
--
-- Mocht je ooit terug willen naar het vault-patroon:
-- select vault.create_secret('<SERVICE-ROLE-KEY>', 'service_role_key');
